name: Deploy Landing Page

on:
  push:
    branches:
      - prod
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            # Klasör yoksa oluştur ve repoyu çek
            if [ ! -d "/var/www/taraftaro-landing-page" ]; then
              sudo mkdir -p /var/www/taraftaro-landing-page
              git clone ${{ github.event.repository.ssh_url }} /var/www/taraftaro-landing-page
            fi

            cd /var/www/taraftaro-landing-page
            git fetch origin ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}
            git clean -fd
